name: Prepare Build

on:
  push:

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: true

      - name: Clean workspace
        run: |
          git clean -fdx
          git reset --hard

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
      - run: yarn cache clean
      - run: yarn install --frozen-lockfile
      - run: yarn build
